name: "Build 🧱"
on:
  workflow_dispatch:

jobs:
  build:
    name: "Flatpak 📦"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.9
      options: --privileged
    steps:
    - name: "Repo checkout"
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: "Validate metadata"
      run: flatpak-builder-lint --exceptions --user-exceptions exceptions.json appstream org.mixxx.Mixxx.Devel.metainfo.xml

    - name: "Validate manifest"
      run: flatpak-builder-lint --exceptions --user-exceptions exceptions.json manifest org.mixxx.Mixxx.Devel.json

    - name: "Build Flatpak"
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Mixxx-Devel.flatpak
        manifest-path: org.mixxx.Mixxx.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
        upload-artifact: false

    - name: "Validate repository"
      run: flatpak-builder-lint --exceptions --user-exceptions exceptions.json repo repo

    - name: "Create debug bundle"
      run: |
        echo "Creating a debug extension bundle..."
        /app/bin/flatpak build-bundle repo \
          --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
          --arch=x86_64 --runtime Mixxx-Devel.Debug.flatpak org.mixxx.Mixxx.Devel.Debug

    - name: "Prepare artifact directory"
      run: |
        mkdir -p pages
        mv Mixxx-Devel.flatpak pages
        mv Mixxx-Devel.Debug.flatpak pages

    - name: "Upload artifact"
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages

  deploy:
    name: "Deploy 🚀"
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Publish to Pages"
        uses: actions/deploy-pages@v4
