name: "Dispatch 🚚"
on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    uses: "./.github/workflows/build.yaml"
    permissions:
      id-token: write
      pages: write
    with:
      bundle_upload: true
      repo_upload: false
      pages_deploy: true
      repo_deploy: true
