name: "Test 🧪"
on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    uses: "./.github/workflows/build.yaml"
    permissions:
      id-token: write
      pages: write
    with:
      bundle_upload: false
      repo_upload: false
      pages_deploy: false
      repo_deploy: true
